### ISSUE TITLE
Character literal quotes lost

### ISSUE THREAD

**Issue by peterschrammel** [tautschnig/fshell-w2t#2]
Quotes require escaping:

echo 'char retval1[13] = { 12,' ',-2,-2,-2,0,0,0,1,1,0,'@',-64 };' >> pals_STARTPALS_ActiveStandby_false-unreach-call.5.ufo.BOUNDED-10.pals.c.mod.c

Example:

./test-gen.sh --graphml-witness ../../results-verified/2ls.2017-11-11_2016.logfiles/sv-comp18.pals_STARTPALS_ActiveStandby_false-unreach-call.5.ufo.BOUNDED-10.pals.c.files/witness.graphml -m32 --propertyfile ../../sv-benchmarks/c/ReachSafety.prp ../../sv-benchmarks/c/seq-mthreaded/pals_STARTPALS_ActiveStandby_false-unreach-call.5.ufo.BOUNDED-10.pals.c

https://sv-comp.sosy-lab.org/2018/results/results-verified/2ls.2017-11-11_2016.logfiles/sv-comp18.pals_STARTPALS_ActiveStandby_false-unreach-call.5.ufo.BOUNDED-10.pals.c.files/witness.graphml

**Comment by tautschnig** [comment]
I believe this has been fixed in https://github.com/tautschnig/fshell-w2t/commit/9b232ed253bcdc3c92e49c8b188487f12815223c, but this happened after 2017-11-11. Hence please to confirm in case more recent runs are available.

**Comment by peterschrammel** [comment]
Seems fixed in latest run.
