### ISSUE TITLE
Linking problem with __inline

### ISSUE THREAD

**Issue by AdvaitaDatar** [tautschnig/fshell-w2t#3]
I observed a linking problem with some of the files getting validated, containing functions defined with keyword  __inline.
For example
__inline void ____startrek_schedule_jobs(void) 

Error generated by fshell-w2t 

/tmp/ccNh9Fio.o: In function `__startrek_hyperperiod':
/tmp/witness.LU6VTK/rekh_ctm_false-unreach-call.2_true-termination.c.mod.c:1937: undefined reference to `**__startrek_schedule_jobs**'
/tmp/witness.LU6VTK/rekh_ctm_false-unreach-call.2_true-termination.c.mod.c:1938: undefined reference to `__startrek_init_globals'
/tmp/ccNh9Fio.o: In function `__orig__main':
/tmp/witness.LU6VTK/rekh_ctm_false-unreach-call.2_true-termination.c.mod.c:2666: undefined reference to `__startrek_user_init'
/tmp/witness.LU6VTK/rekh_ctm_false-unreach-call.2_true-termination.c.mod.c:2741: undefined reference to `__startrek_user_final'
collect2: error: ld returned 1 exit status
tester.mk:13: recipe for target 'tester' failed
make: *** [tester] Error 1
rekh_ctm_false-unreach-call.2_true-termination.c: ERROR - failing assertion not found

As per my understanding fshell-w2t is using c99 standards for compilation and Inline functions is not supported by -std=c99.  Below url provide a way to handle this problem. 

[https://gcc.gnu.org/onlinedocs/gcc-3.3.6/gcc/Alternate-Keywords.html#Alternate-Keywords](url)

Kindly refer the zip containing following -   

 - log file and output file of witness2tess 
 - graphml files generated using CBMC   
 -  false program

[Issue2.zip](https://github.com/tautschnig/fshell-w2t/files/1495264/Issue2.zip)

**Comment by AdvaitaDatar** [comment]
Thanks for the fixes provided. 

I took the latest version to fshell-w2t. The linking issue reported has been fixed, however fshell-w2t  is reporting "TRUE" for the false program. Kindly check. 
Below are the few lines of the output  

//========================================================== 
cc -o tester -g -m32 -std=c99 -fgnu89-inline tester.c pals_opt-floodmax.3_false-unreach-call.1.ufo.UNBOUNDED.pals.c.mod.c
./tester 1
pals_opt-floodmax.3_false-unreach-call.1.ufo.UNBOUNDED.pals.c: ERROR - failing assertion not found
TRUE
//=====================================================

**Comment by tautschnig** [comment]
There are two possible root causes here: 1) the witness is wrong or not sufficiently prescriptive to cause the assertion to fail, or 2) the translation of the witness to a test is broken. Only in the latter case is there anything that could be fixed in fshell-w2t. I'm afraid I will need to make a default assumption of 1 as I'm not sure I have sufficient information to debug this.
